weights: ''
teacher_weights: yolov9-e.pt
teacher_cfg: models/detect/yolov9-e.yaml
cfg: models/detect/yolov9-m.yaml
data: data/coco.yaml
hyp:
  lr0: 0.005
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 6.0
  cls: 0.3
  cls_pw: 1.0
  obj: 0.5
  obj_pw: 1.0
  dfl: 1.5
  iou_t: 0.2
  anchor_t: 5.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.5
  hsv_v: 0.3
  degrees: 0.0
  translate: 0.05
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.8
  mixup: 0.05
  copy_paste: 0.1
epochs: 100
batch_size: 16
imgsz: 640
optimizer: SGD
workers: 8
device: '0'
lambda_kd: 0.1
freeze:
- 0
project: /mnt/ubuntu_hdd/yolov9/runs/train
name: exp
exist_ok: false
save_dir: ''
